
from sqlite3.dbapi2 import SQLITE_IOERR_SHORT_READ


SCREEN_WIDTH = 1500

SCREEN_HEIGHT = 900

LINE_WIDTH = 2

PLAYER_RADIUS = 20

PLAYER_TURN_SPEED = 300

PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.5
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5

PLAYER_SHOOT_SPEED = 500

PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_REVERSE_COOLDOWN_SECONDS = 0.2

DIFFICULTY_INCREMENT_TIMER = 30.0
