
from sqlite3.dbapi2 import SQLITE_IOERR_SHORT_READ


BASE_SCREEN_WIDTH = 1500
BASE_SCREEN_HEIGHT = 900
SCREEN_WIDTH = BASE_SCREEN_WIDTH
SCREEN_HEIGHT = BASE_SCREEN_HEIGHT

LINE_WIDTH = 2

PLAYER_RADIUS = 17.5

PLAYER_TURN_SPEED = 300

PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.5
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5

PLAYER_SHOOT_SPEED = 500

PLAYER_SHOOT_COOLDOWN_SECONDS = 0.22
PLAYER_REVERSE_COOLDOWN_SECONDS = 0.2

DIFFICULTY_INCREMENT_TIMER = 30.0
